"""add event_date column

Revision ID: da4aa9c666dc
Revises: 4340172195f0
Create Date: 2026-03-15 16:02:20.180534

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = "da4aa9c666dc"
down_revision: Union[str, Sequence[str], None] = "4340172195f0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = inspect(bind)
    event_columns = {column["name"] for column in inspector.get_columns("events")}
    event_id_type = next(
        (str(column["type"]).upper() for column in inspector.get_columns("events") if column["name"] == "id"),
        "",
    )

    with op.batch_alter_table("events", schema=None) as batch_op:
        if "event_date" not in event_columns:
            batch_op.add_column(sa.Column("event_date", sa.DateTime(), nullable=True))
        if "UUID" not in event_id_type:
            batch_op.alter_column(
                "id",
                existing_type=sa.NUMERIC(),
                type_=sa.UUID(),
                existing_nullable=False,
            )
        if "volunteer_count" in event_columns:
            batch_op.drop_column("volunteer_count")

    # Participant UUID columns are already correct in current databases used by this app.
    # Skipping the earlier autogenerated participant recast avoids duplicate-key failures
    # on SQLite databases that already store UUID values.


def downgrade() -> None:
       """Downgrade schema."""
       with op.batch_alter_table("participants", schema=None) as batch_op:
              batch_op.alter_column(
                     "event_id",
                     existing_type=sa.UUID(),
                     type_=sa.NUMERIC(),
                     existing_nullable=False,
              )
              batch_op.alter_column(
                     "id",
                     existing_type=sa.UUID(),
                     type_=sa.NUMERIC(),
                     existing_nullable=False,
              )

       with op.batch_alter_table("events", schema=None) as batch_op:
              batch_op.add_column(sa.Column("volunteer_count", sa.INTEGER(), nullable=True))
              batch_op.alter_column(
                     "id",
                     existing_type=sa.UUID(),
                     type_=sa.NUMERIC(),
                     existing_nullable=False,
              )
              batch_op.drop_column("event_date")
